name: Continuous Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows this workflow to be run manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }} 
    strategy:
      matrix:
        config:
        - name: "Windows Latest MSVC"
          artifact: "Windows-MSVC.7z"
          os: windows-latest
          cc: "cl"
          cxx: "cl"
          environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
        - name: "Ubuntu Latest GCC"
          artifact: "Linux.7z"
          os: ubuntu-latest
          cc: "gcc"
          cxx: "g++"
        - name: "macOS Latest Clang"
          artifact: "macOS.7z"
          os: macos-latest
          cc: "clang"
          cxx: "clang++"

    steps:
      - name: Check out csound-vst3-opcodes.
        uses: actions/checkout@v2

      - name: Fetch the current VST3 SDK and Csound sources.
        run: bash update-submodules.bash
        
      - name: Build on Mac OS.
        if: runner.os == 'macOS'
        run: echo "Stub for macOS." #bash clean-build-macos.bash
        
      - name: Build on Linux.
        if: runner.os == 'Linux'
        run: |
          sudo apt install cmake gcc "libstdc++6" libx11-xcb-dev libxcb-util-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
          bash clean-build-linux.bash
        
      - name: Build on Windows.
        if: runner.os == 'Windows'
        run: bash clean-build-windows.bash
        
      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          # Note-worthy description of changes in release
          #body: # optional
          # Path to load note-worthy description of changes in release from
          #body_path: # optional
          # Gives the release a custom name. Defaults to tag name
          name: Test
          # Creates a draft release. Defaults to false
          draft: true
          # Identify the release as a prerelease. Defaults to false
          prerelease: true
          # Newline-delimited list of path globs for asset files to upload
          files: ./build-linux/lib/Debug/libvst3_plugins.so    
          
