name: Continuous Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }} 
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - name: Check out csound-vst3-opcodes.
        uses: actions/checkout@v2

      - name: Fetch the current VST3 SDK and the Csound sources.
        run: bash update-submodules.bash
        
      #- name: Build on Mac OS.
      #  if: runner.os == "macOS"
      #  run: bash clean-build-macos.bash
        
      - name: Build on Linux.
        if: runner.os == "Linux"
        run: bash clean-build-linux.bash
        
      #- name: Build on Windows.
      #  if: runner.os == "Windows"
      #  # Add msbuild to PATH.
      #  uses: microsoft/setup-msbuild@v1.0.2        
      #  run: bash clean-build-windows.bash
        
      - name: Release
        # You may pin to the exact commit or the version.
        uses: softprops/action-gh-release@v0.1.5
        with:
          # Note-worthy description of changes in release
          #body: # optional
          # Path to load note-worthy description of changes in release from
          #body_path: # optional
          # Gives the release a custom name. Defaults to tag name
          #name: # optional
          # Creates a draft release. Defaults to false
          draft: true
          # Identify the release as a prerelease. Defaults to false
          prerelease: true
          # Newline-delimited list of path globs for asset files to upload
          files: ./build-linux/lib/Debug/libvst3_plugins.so    
          
